Add splat to Application::puts parameter
Adding the splat keeps Albacore's puts method in sync with Ruby core's.

Before:
```text
Z:\>bundle exec irb
irb(main):001:0> puts

=> nil
irb(main):002:0> puts :a, 42
a
42
=> nil
irb(main):003:0> require 'albacore'
=> true
irb(main):004:0> puts
ArgumentError: wrong number of arguments (0 for 1)
irb(main):005:0> puts :a, 42
ArgumentError: wrong number of arguments (2 for 1)
```

After:
```text
Z:\>bundle exec irb
irb(main):001:0> puts

=> nil
irb(main):002:0> puts :a, 42
a
42
=> nil
irb(main):003:0> require 'albacore'
=> true
irb(main):004:0> puts

=> nil
irb(main):005:0> puts :a, 42
a
42
=> nil
```